commands:
  open-exchange-menu:
    - "exchange"
    - "ex"
    - "gielda"
    - "giel"
    - "crypto"



menu:
  tittles:
    main-menu:
    portfolio-opened-positions:
    portfolio-closed-positions:
    admin-panel:
    buy_or_sell_crypto:
    pick_crypto_amount:
  menu-sounds:
    menu-open:
    menu-close:
    open-portfolio:
    menu-click:
    buy-crypto:
    sell-crypto:



market:
  #currency for which the crypto will be paired with (supported: USDT, EUR, PLN, TRY, GBP, BRL)
  #the most accurate one and recommended is the USDT
  default-quote-currency: "USDT"

  # Spread is the difference between buy price and sell price, you can put here everything from 0.01% to 99.0%
  spread: 0.05 #percentage

  #list of crypto that will be available for purchase
  #NOTE that if you remove any, the players won't be able to sell them if they bought them before
  #If you want to add a crypto u have to put here their ticker, you want to add Bitcoin -> put BTC
  tracked-cryptos:
    - "BTC"
    - "ETH"
    - "USDT"
    - "BNB"
    - "XRP"
    - "SOL"
    - "USDC"
    - "DOGE"
    - "TRX"
    - "ADA"
    - "MATIC"
    - "LINK"
    - "LTC"
    - "BCH"
    - "XLM"
    - "HBAR"
    - "XMR"
    - "ALGO"
    - "NEAR"
    - "OKB"
    - "LEO"
    - "HYPE"
    - "DAI"

# If MySQL is disabled SQLite will be used instead
MySQL_database:
  enabled: false
  database: "crypto_exchange"
  host: "localhost"
  port: 3306
  user: "root"
  password:
  maximum_connections_hikariCP: 25 #Don't change unless you know what you're doing


